name: QaFramework Trigger
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger QAFramework
        uses: peter-evans/repository-dispatch@v2.1.0
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          repository: openmrs/openmrs-contrib-qaframework
          event-type: qa-initialSetup
